# Generated by Django 5.2.14 on 2026-05-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('cor_hex', models.CharField(blank=True, default='', help_text='Cor opcional para gráfico de pizza, ex: #f97316', max_length=7, verbose_name='cor (hex)')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('CUSTO', 'Custo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Sempre positivo; o sinal vem do tipo (CUSTO/DESPESA saem, RECEITA entra).', max_digits=12, verbose_name='valor')),
                ('data_lancamento', models.DateField(verbose_name='data do lançamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.categoriafinanceira', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'lançamento financeiro',
                'verbose_name_plural': 'lançamentos financeiros',
                'ordering': ['-data_lancamento', '-id'],
                'indexes': [models.Index(fields=['tipo', 'data_lancamento'], name='finance_lan_tipo_65b97b_idx'), models.Index(fields=['status', 'data_lancamento'], name='finance_lan_status_686613_idx')],
            },
        ),
    ]
