# Generated by Django 5.2.14 on 2026-07-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0003_visaogeralperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financeiras', to='accounts.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='accounts.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='visaogeralperiodo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_visao_geral', to='accounts.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_categoria_financeira_nome_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='unique_categoria_financeira_slug_por_empresa'),
        ),
    ]
