# Generated by Django 5.2.14 on 2026-07-08 16:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def preencher_categoria_pela_subcategoria(apps, schema_editor):
    """Produtos que já têm subcategoria herdam a categoria dela."""
    Produto = apps.get_model("catalog", "Produto")
    Subcategoria = apps.get_model("catalog", "Subcategoria")
    Produto.objects.filter(
        categoria__isnull=True, subcategoria__isnull=False
    ).update(
        categoria_id=Subquery(
            Subcategoria.objects.filter(
                pk=OuterRef("subcategoria_id")
            ).values("categoria_id")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_categoria_empresa_marca_empresa_produto_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.categoria', verbose_name='categoria'),
        ),
        migrations.RunPython(
            preencher_categoria_pela_subcategoria,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
